schema: "classroom50/repo-config/v1"
classroom: "indprog"
assignment: "i-know-flowchart"
owner:
  username: "M-Trolle"
  id: 323143885
  accepted_at: "2026-09-02T07:29:00Z"
source:
  owner: "geko-crooms"
  owner_id: 316422449
  repo: "i-know-flowchart"
  branch: "main"
